site_name: 'Komiser'
site_description: 'Cloud Environment Inspector'
site_author: 'Mohamed Labouardy'
site_url: 'https://komiser.io'
copyright: 'Copyright &copy; 2021 Komiser'
theme:
  favicon: 'images/favicon.ico'
  logo: 'images/logo.png'
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
nav:
    - Getting Started: getting_started.md
    - Providers:
        - 'AWS': 'providers/aws.md'
        - 'GCP': 'providers/gcp.md'
        - 'Azure': 'providers/azure.md'
        - 'OVH': 'providers/ovh.md'
        - 'DigitalOcean': 'providers/digitalocean.md'
    - Komiser Cloud: komiser_cloud.md
    - Alerts: alerts.md
    - Tutorials: tutorials.md
    - Contributing: contributing.md
markdown_extensions:
  - admonition
repo_name: 'mlabouardy/komiser'
repo_url: 'https://github.com/mlabouardy/komiser'
extra:
  analytics:
    provider: google
    property: UA-57902136-18
  social:
    - type: 'github'
      icon: fontawesome/brands/github
      link: 'https://github.com/mlabouardy/komiser'
    - type: 'discord'
      icon: fontawesome/brands/discord
      link: 'https://discord.oraculi.io/'
    - type: 'twitter'
      icon: fontawesome/brands/twitter
      link: 'https://twitter.com/HelloOraculi'
    - type: 'linkedin'
      icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/company/hellooraculi/about'