version: 2.1

executors:
  environment:
    docker:
      - image: node:18.7.0
    resource_class: large
    working_directory: ~/docs.komiser.io

jobs:
  build:
    executor: environment
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build website
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    executor: environment
    steps:
      - attach_workspace:
          at: build
      - run:
          name: Install AWS CLI
          command: |
            apt-get update
            apt-get install -y awscli
      - run:
          name: Push to S3 bucket
          command: |
            cd build/
            aws s3 cp --recursive build/ s3://www.docs.komiser.io --region eu-central-1
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id E3EWXSQNWBIVSU --paths "/*"

workflows:
  ci_cd:
    jobs:
      - build:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
