version: 2.1


executors:
  environment:
    docker:
      - image: node:14.15.1
    resource_class: large
    working_directory: ~/docs.komiser.io

jobs:
  build:
    executor: environment
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build website
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli
      - run:
          name: Push to S3 bucket
          command: |
            aws s3 cp --recursive build/ s3://www.docs.komiser.io --region eu-central-1
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id E3EWXSQNWBIVSU --paths "/*"